export const RING = 'RING';
export const STOP_RINGING = 'STOP_RINGING';

export const START_CALL = 'START_CALL';
export const SET_VIDEO_CALL_ROOM_ID = 'SET_VIDEO_CALL_ROOM_ID';
export const SET_RTC_OFFER = 'SET_RTC_OFFER';
export const SET_RTC_ANSWER = 'SET_RTC_ANSWER';
export const SET_RTC_CANDIDATE = 'SET_RTC_CANDIDATE';
export const ACCEPT_CALL = 'ACCEPT_CALL';

export const CALL_CONNECTED = 'CALL_CONNECTED';
export const CALL_DISCONNECTED = 'CALL_DISCONNECTED';
export const ADD_VIDEOCALL_MSG = 'ADD_VIDEOCALL_MSG';

export const ZOOM_TO_FULLSCREEN = 'ZOOM_TO_FULLSCREEN';
export const EXIT_FULLSCREEN = 'EXIT_FULLSCREEN';
export const SET_IS_ADDING_NEW_PEER_TO_CALL = 'SET_IS_ADDING_NEW_PEER_TO_CALL';
export const END_CALL = 'END_CALL';
export const RESET_VIDEOCALL_STATE = 'RESET_VIDEOCALL_STATE';
